version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - revive
    - gosec
    - gocritic
    - misspell
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gosec:
    excludes:
      - G404

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"

  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - commentedOutCode

  misspell:
    locale: US

formatters-settings:
  goimports:
    local-prefixes:
      - github.com/dpleshakov/auspex

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gosec
        - gocritic

    - path: "internal/store/"
      linters:
        - all
