version: "2"

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/dpleshakov/auspex

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - revive
    - gosec
    - gocritic
    - misspell
    - whitespace

  settings:
    gosec:
      excludes:
        - G404

    revive:
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers"

    gocritic:
      enabled-tags:
        - diagnostic
        - style
      disabled-checks:
        - commentedOutCode

    misspell:
      locale: US

  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - gosec
          - gocritic

      - path: "internal/store/"
        linters:
          - all

      - linters:
          - revive
        path: internal/api/
        text: "avoid meaningless package names"
