// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package store

import (
	"context"
	"time"
)

const deleteCharacter = `-- name: DeleteCharacter :exec
DELETE FROM characters WHERE id = ?
`

func (q *Queries) DeleteCharacter(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCharacter, id)
	return err
}

const getCharacter = `-- name: GetCharacter :one

SELECT id, name, access_token, refresh_token, token_expiry, created_at, corporation_id, corporation_name
FROM characters
WHERE id = ?
`

// sqlc queries for the characters table.
// See https://docs.sqlc.dev for query annotation syntax.
func (q *Queries) GetCharacter(ctx context.Context, id int64) (Character, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.CreatedAt,
		&i.CorporationID,
		&i.CorporationName,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, name, access_token, refresh_token, token_expiry, created_at, corporation_id, corporation_name
FROM characters
ORDER BY name
`

func (q *Queries) ListCharacters(ctx context.Context) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.CreatedAt,
			&i.CorporationID,
			&i.CorporationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersByCorporation = `-- name: ListCharactersByCorporation :many
SELECT id, name, access_token, refresh_token, token_expiry, created_at, corporation_id, corporation_name
FROM characters
WHERE corporation_id = ?
ORDER BY name
`

func (q *Queries) ListCharactersByCorporation(ctx context.Context, corporationID int64) ([]Character, error) {
	rows, err := q.db.QueryContext(ctx, listCharactersByCorporation, corporationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.CreatedAt,
			&i.CorporationID,
			&i.CorporationName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCharactersWithMeta = `-- name: ListCharactersWithMeta :many
SELECT
  ch.id,
  ch.name,
  ch.corporation_id,
  ch.corporation_name,
  ch.created_at,
  CASE WHEN corp.id IS NOT NULL THEN 1 ELSE 0 END AS is_delegate,
  CASE WHEN corp.id IS NOT NULL THEN (
    SELECT last_error FROM sync_state
    WHERE owner_type = 'corporation' AND owner_id = ch.corporation_id AND last_error IS NOT NULL
    LIMIT 1
  ) ELSE NULL END AS sync_error
FROM characters ch
LEFT JOIN corporations corp ON corp.delegate_id = ch.id
ORDER BY ch.name
`

type ListCharactersWithMetaRow struct {
	ID              int64
	Name            string
	CorporationID   int64
	CorporationName string
	CreatedAt       time.Time
	IsDelegate      int64
	SyncError       interface{}
}

func (q *Queries) ListCharactersWithMeta(ctx context.Context) ([]ListCharactersWithMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, listCharactersWithMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCharactersWithMetaRow
	for rows.Next() {
		var i ListCharactersWithMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CorporationID,
			&i.CorporationName,
			&i.CreatedAt,
			&i.IsDelegate,
			&i.SyncError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCharacter = `-- name: UpsertCharacter :exec
INSERT INTO characters (id, name, access_token, refresh_token, token_expiry, corporation_id, corporation_name)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name             = excluded.name,
    access_token     = excluded.access_token,
    refresh_token    = excluded.refresh_token,
    token_expiry     = excluded.token_expiry,
    corporation_id   = excluded.corporation_id,
    corporation_name = excluded.corporation_name
`

type UpsertCharacterParams struct {
	ID              int64
	Name            string
	AccessToken     string
	RefreshToken    string
	TokenExpiry     time.Time
	CorporationID   int64
	CorporationName string
}

func (q *Queries) UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) error {
	_, err := q.db.ExecContext(ctx, upsertCharacter,
		arg.ID,
		arg.Name,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.CorporationID,
		arg.CorporationName,
	)
	return err
}
