// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: corporations.sql

package store

import (
	"context"
	"time"
)

const deleteCorporation = `-- name: DeleteCorporation :exec
DELETE FROM corporations WHERE id = ?
`

func (q *Queries) DeleteCorporation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCorporation, id)
	return err
}

const getCorporation = `-- name: GetCorporation :one

SELECT id, name, delegate_id, created_at
FROM corporations
WHERE id = ?
`

// sqlc queries for the corporations table.
// See https://docs.sqlc.dev for query annotation syntax.
func (q *Queries) GetCorporation(ctx context.Context, id int64) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, getCorporation, id)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DelegateID,
		&i.CreatedAt,
	)
	return i, err
}

const insertCorporation = `-- name: InsertCorporation :exec
INSERT INTO corporations (id, name, delegate_id)
VALUES (?, ?, ?)
`

type InsertCorporationParams struct {
	ID         int64
	Name       string
	DelegateID int64
}

func (q *Queries) InsertCorporation(ctx context.Context, arg InsertCorporationParams) error {
	_, err := q.db.ExecContext(ctx, insertCorporation, arg.ID, arg.Name, arg.DelegateID)
	return err
}

const listCorporations = `-- name: ListCorporations :many
SELECT c.id, c.name, c.delegate_id, ch.name AS delegate_name, c.created_at
FROM corporations c
JOIN characters ch ON ch.id = c.delegate_id
ORDER BY c.name
`

type ListCorporationsRow struct {
	ID           int64
	Name         string
	DelegateID   int64
	DelegateName string
	CreatedAt    time.Time
}

func (q *Queries) ListCorporations(ctx context.Context) ([]ListCorporationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCorporations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCorporationsRow
	for rows.Next() {
		var i ListCorporationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DelegateID,
			&i.DelegateName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
