// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: corp_assets.sql

package store

import (
	"context"
)

const deleteCorpAssetsByOwner = `-- name: DeleteCorpAssetsByOwner :exec
DELETE FROM corp_assets WHERE owner_id = ?
`

func (q *Queries) DeleteCorpAssetsByOwner(ctx context.Context, ownerID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCorpAssetsByOwner, ownerID)
	return err
}

const getCorpAsset = `-- name: GetCorpAsset :one
SELECT location_id, location_type FROM corp_assets WHERE item_id = ?
`

type GetCorpAssetRow struct {
	LocationID   int64
	LocationType string
}

func (q *Queries) GetCorpAsset(ctx context.Context, itemID int64) (GetCorpAssetRow, error) {
	row := q.db.QueryRowContext(ctx, getCorpAsset, itemID)
	var i GetCorpAssetRow
	err := row.Scan(&i.LocationID, &i.LocationType)
	return i, err
}

const upsertCorpAsset = `-- name: UpsertCorpAsset :exec

INSERT OR REPLACE INTO corp_assets (item_id, owner_id, location_id, location_type)
VALUES (?, ?, ?, ?)
`

type UpsertCorpAssetParams struct {
	ItemID       int64
	OwnerID      int64
	LocationID   int64
	LocationType string
}

// sqlc queries for the corp_assets table.
func (q *Queries) UpsertCorpAsset(ctx context.Context, arg UpsertCorpAssetParams) error {
	_, err := q.db.ExecContext(ctx, upsertCorpAsset,
		arg.ItemID,
		arg.OwnerID,
		arg.LocationID,
		arg.LocationType,
	)
	return err
}
