// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type Blueprint struct {
	ID         int64
	OwnerType  string
	OwnerID    int64
	TypeID     int64
	LocationID int64
	MeLevel    int64
	TeLevel    int64
	UpdatedAt  time.Time
}

type Character struct {
	ID              int64
	Name            string
	AccessToken     string
	RefreshToken    string
	TokenExpiry     time.Time
	CreatedAt       time.Time
	CorporationID   int64
	CorporationName string
}

type Corporation struct {
	ID         int64
	Name       string
	DelegateID int64
	CreatedAt  time.Time
}

type EveCategory struct {
	ID   int64
	Name string
}

type EveGroup struct {
	ID         int64
	CategoryID int64
	Name       string
}

type EveLocation struct {
	ID         int64
	Name       string
	ResolvedAt time.Time
}

type EveType struct {
	ID      int64
	GroupID int64
	Name    string
}

type Job struct {
	ID          int64
	BlueprintID int64
	OwnerType   string
	OwnerID     int64
	InstallerID int64
	Activity    string
	Status      string
	StartDate   time.Time
	EndDate     time.Time
	UpdatedAt   time.Time
}

type SyncState struct {
	OwnerType  string
	OwnerID    int64
	Endpoint   string
	LastSync   time.Time
	CacheUntil time.Time
	LastError  sql.NullString
}
