// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CountCompletingToday(ctx context.Context) (int64, error)
	CountIdleBlueprints(ctx context.Context) (int64, error)
	CountOverdueJobs(ctx context.Context) (int64, error)
	DeleteBlueprintsByOwner(ctx context.Context, arg DeleteBlueprintsByOwnerParams) error
	DeleteCharacter(ctx context.Context, id int64) error
	DeleteCorporation(ctx context.Context, id int64) error
	DeleteJobByID(ctx context.Context, id int64) error
	DeleteJobsByOwner(ctx context.Context, arg DeleteJobsByOwnerParams) error
	DeleteSyncStateByOwner(ctx context.Context, arg DeleteSyncStateByOwnerParams) error
	// sqlc queries for the characters table.
	// See https://docs.sqlc.dev for query annotation syntax.
	GetCharacter(ctx context.Context, id int64) (Character, error)
	// sqlc queries for the corporations table.
	// See https://docs.sqlc.dev for query annotation syntax.
	GetCorporation(ctx context.Context, id int64) (Corporation, error)
	GetEveType(ctx context.Context, id int64) (EveType, error)
	// sqlc queries for the sync_state table.
	// See https://docs.sqlc.dev for query annotation syntax.
	GetSyncState(ctx context.Context, arg GetSyncStateParams) (SyncState, error)
	InsertCorporation(ctx context.Context, arg InsertCorporationParams) error
	// sqlc queries for eve_types, eve_groups, eve_categories tables.
	// See https://docs.sqlc.dev for query annotation syntax.
	InsertEveCategory(ctx context.Context, arg InsertEveCategoryParams) error
	InsertEveGroup(ctx context.Context, arg InsertEveGroupParams) error
	InsertEveType(ctx context.Context, arg InsertEveTypeParams) error
	ListBlueprintTypeIDsByOwner(ctx context.Context, arg ListBlueprintTypeIDsByOwnerParams) ([]int64, error)
	ListBlueprints(ctx context.Context, arg ListBlueprintsParams) ([]ListBlueprintsRow, error)
	ListCharacterSlotUsage(ctx context.Context) ([]ListCharacterSlotUsageRow, error)
	ListCharacters(ctx context.Context) ([]Character, error)
	ListCorporations(ctx context.Context) ([]ListCorporationsRow, error)
	ListJobIDsByOwner(ctx context.Context, arg ListJobIDsByOwnerParams) ([]int64, error)
	ListSyncStatus(ctx context.Context) ([]ListSyncStatusRow, error)
	// sqlc queries for the blueprints table.
	// See https://docs.sqlc.dev for query annotation syntax.
	UpsertBlueprint(ctx context.Context, arg UpsertBlueprintParams) error
	UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) error
	// sqlc queries for the jobs table.
	// See https://docs.sqlc.dev for query annotation syntax.
	UpsertJob(ctx context.Context, arg UpsertJobParams) error
	UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) error
}

var _ Querier = (*Queries)(nil)
