// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: universe.sql

package store

import (
	"context"
)

const getEveType = `-- name: GetEveType :one
SELECT id, group_id, name FROM eve_types WHERE id = ?
`

func (q *Queries) GetEveType(ctx context.Context, id int64) (EveType, error) {
	row := q.db.QueryRowContext(ctx, getEveType, id)
	var i EveType
	err := row.Scan(&i.ID, &i.GroupID, &i.Name)
	return i, err
}

const insertEveCategory = `-- name: InsertEveCategory :exec

INSERT OR IGNORE INTO eve_categories (id, name) VALUES (?, ?)
`

type InsertEveCategoryParams struct {
	ID   int64
	Name string
}

// sqlc queries for eve_types, eve_groups, eve_categories tables.
// See https://docs.sqlc.dev for query annotation syntax.
func (q *Queries) InsertEveCategory(ctx context.Context, arg InsertEveCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertEveCategory, arg.ID, arg.Name)
	return err
}

const insertEveGroup = `-- name: InsertEveGroup :exec
INSERT OR IGNORE INTO eve_groups (id, category_id, name) VALUES (?, ?, ?)
`

type InsertEveGroupParams struct {
	ID         int64
	CategoryID int64
	Name       string
}

func (q *Queries) InsertEveGroup(ctx context.Context, arg InsertEveGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertEveGroup, arg.ID, arg.CategoryID, arg.Name)
	return err
}

const insertEveType = `-- name: InsertEveType :exec
INSERT OR IGNORE INTO eve_types (id, group_id, name) VALUES (?, ?, ?)
`

type InsertEveTypeParams struct {
	ID      int64
	GroupID int64
	Name    string
}

func (q *Queries) InsertEveType(ctx context.Context, arg InsertEveTypeParams) error {
	_, err := q.db.ExecContext(ctx, insertEveType, arg.ID, arg.GroupID, arg.Name)
	return err
}
